name: 部署文件到服务器
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        cache: pnpm

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: |
        pnpm build
        cat .next/BUILD_ID

    - name: Deploy to Server
      uses: lexmin0412/ssh-deploy@master
      with: # 以下为参数
        USERNAME: ${{ secrets.DEPLOY_USER }}
        PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        SOURCE: .next
        TARGET: /cellerchan.top/backend/guard/.next
        AFTER_COMMAND: 'cd /cellerchan.top && pm2 restart guard'
